# Generated by Django 2.2 on 2020-05-03 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fav_books_app', '0003_auto_20200503_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.CharField(default='null=true', max_length=255),
            preserve_default=False,
        ),
    ]
